spring:
  application.name: gateway
sopp:
  server:
    auth:
      url: http://35.188.91.10:80/verify
    wallet:
      url: http://34.122.25.144:80/wallet
    payment:
      url:  http://34.41.35.12/payment
    notification:
      url: http://localhost:8084/notification/token
server:
  port: 8070
firebase:
  credentials:
    path: serviceAccountKey.json
